### ISSUE TITLE
project uses nightly, but that's not specified 

### ISSUE THREAD

**Issue by eclbg** [sitano/maelstrom-rust-node#2]
Thanks so much for putting this together. I am working through Gossip Glomers in Rust and will start using your library now that I've reached Challenge 4. I
 have been browsing through the code and it seems to me that the project uses rust nightly, but that's not specified in a `rust-toolchain.toml` file

Cheers and thanks again!

**Comment by sitano** [comment]
Thank you @eclbg for the comment! I used nightly at the beginning when I had to choose between `async_trait` and https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html. But this RFC lacks some functionality that I needed really hard. I, however, don't remember which one. What I actually wanted was to have Map<> of FnPtr's to async functions, but I did not find an easy way to implement that. So I ended up with `async_trait` crate which works well.

Finally, I have decided to get rid of pin! which is unstable in https://github.com/sitano/maelstrom-rust-node/commit/0751c3f8ed1c5336b96a9cc444789e7b55901f59, and now we can compile everything with stable toolchain. 

I hope these challenges will bring joy to you. Have fun!

**Comment by eclbg** [comment]
Thanks! I am doing a deep dive on your repository and it's being a very educational experience—really appreciate you building the library. 
I wonder if you could enable "discussions" on the repository? I would like to ask a question about how the code works (I can't figure out how the communication with maelstrom-provided KV services works) and feel like `issues` is not the right place for it. Should I just ask the question here maybe?

**Comment by eclbg** [comment]
Thanks! I am doing a deep dive on your repository and it's being a very educational experience—really appreciate you building the library. 
I wonder if you could enable "discussions" on the repository? I would like to ask a question about how the code works (I can't figure out how the communication with maelstrom-provided KV services works) and feel like `issues` is not the right place for it. Should I just ask the question here maybe?

**Comment by sitano** [comment]
>  can't figure out how the communication with maelstrom-provided KV services works

of course, ask questions somewhere (ie in discussions) - I will answer.

**Comment by sitano** [comment]
@eclbg I am curious Enric, how did you find this lib? via Maelstrom Rust demos or via local Barcelona RustBcn meetup?

**Comment by eclbg** [comment]
I must have found it just googling gossip glomers rust. I later saw that you've been quite active in the fly.io forums and that [Ben Johnson](https://twitter.com/benbjohnson) tweeted about it. I started solving the challenges following Jon Gjengset's [video](https://youtu.be/gboGyccRVXI) which only gets to challenge 3, and I was struggling to interact with Maelstrom-provided KV following his approach for Challenge 4.

I'm very new to Rust and this is the first time that I read code that uses tokio (and I know very little async in general), so I don't fully understand how the node receives responses to messages it sends to the KV. What I'll do is try to solve challenges 1-4 using your library and if I succeed but still don't understand how it works I'll come back to ask the question.

**Comment by sitano** [comment]
Nice! I didn't know there is a video by Jon.

> so I don't fully understand how the node receives responses to messages it sends to the KV

ask questions in the Discussions section. here or at the forum. I will try to answer them. I can recommend taking a look at the /examples folder for KV examples in the repo. I will share how RPC / KV works. It is relatively not very complicated.

**Comment by sitano** [comment]
https://github.com/sitano/maelstrom-rust-node/blob/main/examples/lin_kv.rs

**Comment by sitano** [comment]
Remember also that the messages to the KV are exactly the same as any other kind of RPC messages - messages with msg_id and type. They are received and parsed exactly as any other normal message. KV storages are just another nodes in the cluster.
